### ISSUE TITLE
tesaro - issue

### ISSUE THREAD

**Issue by tsandu** [RoxieAtRubrik/hello-world#216]
**Describe the bug**
so many tools for github.. why? do i care? why should i care? how does this help me in my business?

**Comment by RoxieAtRubrik** [comment]
Great question!

GitHub is a distributed version control system. Rather than have only one single place for the full version history of the software, the working copy of the code is a repository that can contain the full history of all changes. Rather than simply using Git, a benefit of GitHub is the social code-hosting aspect. Not only can you browse other projects, but you can contribute, comment, like, and be socially involved.

This is helpful for maintaining any documentation, code, or scripts used within your business. GitHub is not the only distributed version control system available; some companies go for BitBucket or other alternatives. However, keep in mind that the user flow is the same regardless since these are all based on Git.
